linters:
  fast: false

  enable:
    - asasalint
    - asciicheck
    - bidichk
    - bodyclose
    - contextcheck
    - durationcheck
    - errcheck
    - errorlint
    - exportloopref
    - godot
    - gofmt
    - gofumpt
    - goimports
    - gomoddirectives
    - gosec
    - gosimple
    - govet
    - interfacer
    - misspell
    - nakedret
    - nilerr
    - nilnil
    - noctx
    - nolintlint
    - prealloc
    - predeclared
    - promlinter
    - reassign
    - rowserrcheck
    - sqlclosecheck
    - staticcheck
    - stylecheck
    - tenv
    - testableexamples
    - thelper
    - tparallel
    - unconvert
    - unparam
    - unused
  disable:
    - wastedassign
    - gocritic
    - ineffassign
    - errname
    - usestdlibvars
    - containedctx
    - cyclop
    - deadcode
    - decorder
    - depguard
    - dogsled
    - dupl
    - revive
    - dupword
    - errchkjson
    - execinquery
    - exhaustive
    - exhaustivestruct
    - forbidigo
    - forcetypeassert
    - funlen
    - gci
    - ginkgolinter
    - gocheckcompilerdirectives
    - gochecknoglobals
    - gochecknoinits
    - gocognit
    - goconst
    - gocyclo
    - godox
    - goerr113
    - goheader
    - golint
    - gomnd
    - gomodguard
    - goprintffuncname
    - grouper
    - ifshort
    - importas
    - interfacebloat
    - ireturn
    - lll
    - loggercheck
    - tagliatelle
    - maintidx
    - makezero
    - maligned
    - musttag
    - nestif
    - nlreturn
    - nonamedreturns
    - nosnakecase
    - nosprintfhostport
    - paralleltest
    - testpackage
    - typecheck
    - varnamelen
    - whitespace
    - wrapcheck
    - wsl